export const site = {
  name: "Welya AI",
  shortName: "Welya",
  tagline: "The AI secretary for university students",
  description:
    "Welya AI reads lecturer emails, class group messages and course documents, then turns them into tasks, deadlines and a planned week. An AI academic secretary built for university students.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://welya.app",
  appUrl: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:1420",
  email: "hello@welya.app",
  twitter: "@welyaai",
  locale: "en_US",
  keywords: ["AI secretary for students", "student task manager", "AI planner for university", "deadline reminder app", "class schedule planner", "academic assistant AI", "student to-do app", "Welya AI"],
}

export const nav = {
  main: [
    { href: "/features", label: "Features" },
    { href: "/how-it-works", label: "How it works" },
    { href: "/download", label: "Download" },
    { href: "/blog", label: "Blog" },
    { href: "/faq", label: "FAQ" },
  ],
  footer: [
    { title: "Product", links: [{ href: "/features", label: "Features" }, { href: "/how-it-works", label: "How it works" }, { href: "/download", label: "Download" }, { href: "/changelog", label: "Changelog" }] },
    { title: "Company", links: [{ href: "/about", label: "About" }, { href: "/blog", label: "Blog" }, { href: "/contact", label: "Contact" }, { href: "/security", label: "Security" }] },
    { title: "Legal", links: [{ href: "/privacy", label: "Privacy Policy" }, { href: "/terms", label: "Terms of Service" }] },
  ],
}

export type Feature = { slug: string; eyebrow: string; title: string; description: string; bullets: string[]; screenshot: string; screenshotLight?: string }

export const features: Feature[] = [
  {
    slug: "inbox",
    eyebrow: "Capture → Understand",
    title: "One inbox for everything your lecturers send",
    description: "Lecturer emails, WhatsApp group messages, PDFs and screenshots land in one place. Welya reads each item and explains what it is: an assignment, a schedule change, an exam announcement, or just a note.",
    bullets: ["Detects the type: task, schedule, exam, administrative", "Extracts course, date, time and location automatically", "Shows a confidence score — you stay in control", "One click to create a task, event, reminder or note"],
    screenshot: "/screenshots/inbox-dark.png",
    screenshotLight: "/screenshots/inbox-light.png",
  },
  {
    slug: "dashboard",
    eyebrow: "Organize",
    title: "Your daily command center",
    description: "Open Welya and instantly know what's due today, which classes you have, how much you've finished, and what Welya recommends working on right now.",
    bullets: ["Today's timeline: classes, deadlines, work sessions", "Priority tasks with progress and subtasks", "AI recommendations based on your actual free time", "Quick add: task, note, event, upload"],
    screenshot: "/screenshots/dashboard-dark.png",
    screenshotLight: "/screenshots/dashboard-light.png",
  },
  {
    slug: "calendar",
    eyebrow: "Plan",
    title: "A calendar that knows when you can actually work",
    description: "Welya finds the gaps between your classes and fills them with focused sessions for the most urgent tasks. Not just a calendar — a planner that understands your course load.",
    bullets: ["Plan my day / Plan my week in one click", "Month, week, day and agenda views", "Sessions sized to each task's remaining effort", "Review the plan before anything hits your calendar"],
    screenshot: "/screenshots/calendar-dark.png",
  },
  {
    slug: "tasks",
    eyebrow: "Act",
    title: "Big assignments, broken into checkable steps",
    description: "A task like \"Practicum Report – Module 4\" becomes a list of subtasks you can tick off. Complete with time estimates, attachments, the message it came from, and your notes.",
    bullets: ["Break this task down — subtasks generated by AI", "Views: today, upcoming, overdue, completed", "Linked to courses and workspaces", "Schedule a work session straight from the task"],
    screenshot: "/screenshots/tasks-dark.png",
  },
  {
    slug: "assistant",
    eyebrow: "Ask",
    title: "An assistant that knows your schedule and tasks",
    description: "Ask \"what should I work on today?\" and Welya answers from the tasks, classes and free time you actually have — then offers actions it can run for you.",
    bullets: ["Grounded: answers only from your data, never invents", "Executable actions: plan the day, open a task, break it down", "Context per course, workspace or document", "Conversation history is saved"],
    screenshot: "/screenshots/assistant-dark.png",
  },
  {
    slug: "courses",
    eyebrow: "Context",
    title: "Every course has its own space",
    description: "Schedule, lecturer, tasks, materials, notes, announcements and calendar per course — plus an AI you can ask specifically about that course.",
    bullets: ["Semester progress per course", "Materials and notes linked to tasks", "Inbox announcements grouped automatically", "Ask Welya: \"what's the next deadline?\""],
    screenshot: "/screenshots/course-dark.png",
  },
  {
    slug: "documents",
    eyebrow: "Extract",
    title: "Documents you can talk to",
    description: "Upload slides, a PDF brief or an LMS screenshot. Welya extracts the text, summarizes it, finds the tasks and deadlines inside, and drafts notes.",
    bullets: ["Summarize, extract tasks, extract deadlines, create notes", "Automatic PDF text extraction", "Linked to the related course and tasks", "Chat directly with the document"],
    screenshot: "/screenshots/documents-dark.png",
  },
  {
    slug: "review",
    eyebrow: "Review",
    title: "A weekly review that feels personal",
    description: "Each week Welya sums up what got done, what slipped, your busiest day, and one concrete suggestion — like a secretary closing the week with you.",
    bullets: ["Completed vs remaining vs overdue", "Load per day and per course", "Planned vs completed work", "A specific suggestion for next week"],
    screenshot: "/screenshots/review-dark.png",
  },
]

export const pipeline = [
  { step: "01", title: "Capture", text: "Email, message, PDF, screenshot or a quick paste — everything lands in Welya's Inbox." },
  { step: "02", title: "Understand", text: "The AI reads it and identifies the type, course, date, time and the suggested action." },
  { step: "03", title: "Organize", text: "You confirm; Welya creates linked tasks, events, reminders or notes." },
  { step: "04", title: "Plan", text: "Welya finds free time between classes and schedules focused work sessions." },
  { step: "05", title: "Act", text: "Work from a prioritized list; split big tasks into checkable subtasks." },
  { step: "06", title: "Review", text: "End the week knowing what you achieved and what's coming next." },
]

export const testimonials = [
  { name: "Nadia P.", role: "Informatics, 5th semester", quote: "Deadlines used to get buried in the class group chat. Now every lecturer message turns into a task with the right date. It genuinely feels like having a secretary." },
  { name: "Raka D.", role: "Electrical Engineering, 3rd semester", quote: "Plan my week is wild. It looks at my class schedule and fills the gaps with whatever's due soonest." },
  { name: "Sari M.", role: "Management, 7th semester", quote: "Uploaded a 30-page thesis brief and Welya pulled out every deadline. Saved me an entire afternoon." },
]

export const stats = [
  { value: "6", label: "information sources supported" },
  { value: "< 5 s", label: "from lecturer message to scheduled task" },
  { value: "100%", label: "of decisions stay with you" },
  { value: "0", label: "tasks slipping through without a reminder" },
]

export const faqs = [
  { q: "What is Welya AI?", a: "Welya is an AI academic secretary. It takes in information from emails, messages and documents, understands it, and turns it into connected tasks, deadlines and schedules — so you don't have to record everything by hand." },
  { q: "Does Welya make decisions without me?", a: "No. Welya interprets and suggests; you confirm. Every inbox item shows a confidence score and a recommended action. You can allow very-high-confidence items to be auto-confirmed in Settings." },
  { q: "Which languages are supported?", a: "Welya understands messages in English and Indonesian (including the mixed language typical of class group chats) and replies in the language you write in." },
  { q: "Which information sources are supported?", a: "Today: manual input/paste, PDF uploads, Word documents, plain text, screenshots and Gmail. Google Calendar and Google Tasks sync both ways — what you plan in Welya appears in Google, and what you add in Google appears in Welya. Connect them from the Integrations page inside the app." },
  { q: "Is my data safe?", a: "Your data lives in your own account in our database and is only accessible with your login token. Uploaded files are stored on Welya's server and can only be downloaded by their owner. You can export everything as JSON or delete your account and all its data at any time from Settings → Privacy." },
  { q: "Which AI model powers Welya?", a: "Welya uses a language model through Azure AI Foundry with strictly structured responses, always constrained to your own academic data. If the AI service is unavailable, Welya falls back to its built-in rule engine so the app keeps working." },
  { q: "Is there a desktop app?", a: "Yes. Welya is available as a web app and as a lightweight desktop app (built with Tauri) for Windows, macOS and Linux. See the Download page." },
  { q: "How much does it cost?", a: "Nothing. Welya is completely free for students — every feature, no paid tier, no credit card, no hidden limits." },
]

export const changelog = [
  {
    version: "0.2.0",
    date: "2026-09-20",
    title: "Backend, authentication and AI via Azure AI Foundry",
    items: ["Fastify + PostgreSQL API with optimistic sync (React Query)", "Login, sign-up, email verification and password reset", "Chat, inbox interpretation, task breakdown, document analysis and the weekly review powered by gpt-5-mini", "PDF uploads with text extraction", "Markdown-formatted AI replies", "Custom Welya icon set and logo"],
  },
  {
    version: "0.1.0",
    date: "2026-09-12",
    title: "Welya V2 is born",
    items: ["Dashboard, Inbox, Tasks, Calendar, Courses, Workspaces, Assistant", "Notes & Documents, Notifications, Review, Settings, Integrations", "Desktop app with Tauri 2", "Light/dark theme with shadcn/ui"],
  },
]

export type Post = { slug: string; title: string; excerpt: string; date: string; readingTime: string; tags: string[]; body: string[] }

export const posts: Post[] = [
  {
    slug: "why-todo-lists-fail-students",
    title: "Why ordinary to-do lists fail university students",
    excerpt: "It isn't a discipline problem. Assignment information arrives from five different places, and nobody writes it down for you.",
    date: "2026-09-15",
    readingTime: "5 min read",
    tags: ["Productivity", "University"],
    body: [
      "Every student knows the pattern: a lecturer announces a deadline mid-class, a teaching assistant posts a revision in the WhatsApp group at 11 pm, and the group project brief arrives as a 12-page PDF. None of that information moves itself into a to-do list.",
      "To-do lists assume you are your own secretary: read, understand, translate into a task, set a date, then remind yourself. That's a full-time job — and exactly the job that gets skipped when you're busiest.",
      "Welya was built from that simple observation. Instead of asking you to record things, it takes the information (emails, messages, documents) and does the secretarial part: recognises the type, matches the course, pulls out the date and time, and proposes an action. You just confirm.",
      "The result isn't a longer list. It's a complete one — and a calendar that already knows when you have time to work on it.",
    ],
  },
  {
    slug: "how-plan-my-week-fills-your-free-time",
    title: "Plan my week: how Welya fills the gaps between classes",
    excerpt: "Behind one button is a simple algorithm that respects your timetable, task durations and deadline priority.",
    date: "2026-09-18",
    readingTime: "4 min read",
    tags: ["Feature", "Planning"],
    body: [
      "Most calendar apps show you free time. Welya fills it. When you press Plan my week, it scans 08:00–18:00 for the next five weekdays and looks for gaps of at least an hour between classes and existing events.",
      "Unfinished tasks are sorted by priority, then deadline. For each gap Welya takes the most urgent task, computes the remaining effort from its estimate and progress, and creates a work session of at most two hours with a 15-minute buffer.",
      "Everything is shown first as a proposal you can tick or untick. Nothing touches your calendar until you agree. Once accepted, sessions appear as work blocks linked to their task — and Welya will offer to start one when the time comes.",
    ],
  },
  {
    slug: "ai-that-does-not-make-things-up",
    title: "AI that doesn't make things up: how Welya keeps answers grounded",
    excerpt: "Language models are great at stringing words together, but a secretary who invents deadlines is a disaster. Here's how we prevent it.",
    date: "2026-09-20",
    readingTime: "6 min read",
    tags: ["AI", "Engineering"],
    body: [
      "Every request to Welya's model includes a context block built from your account: open tasks with deadlines in local time, today's schedule, free slots, unprocessed inbox items and relevant documents. The model is instructed to answer only from that block.",
      "Replies are requested in a strict JSON schema: the answer text, a list of references (task/document ids) and actions the app can execute. Before anything is shown, the server verifies that every referenced id really exists. References to tasks that never existed are dropped.",
      "If the model service is unavailable or the answer fails validation, Welya falls back to a deterministic rule engine that produces an equally useful reply, and labels its source. You never see an empty screen.",
      "This approach makes Welya trustworthy for the things that matter: dates, course names, and what you actually need to do today.",
    ],
  },
]
